FROM node:latest
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .
RUN npm install
# Copy app files
COPY public/* public/
COPY src/* src/
COPY tsconfig.json .
# Expose port
EXPOSE 3000
# Start the app
CMD [ "npm", "start" ]