FROM node:latest
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn --silent
# Copy app files
COPY src/* src/
COPY tsconfig.json .
COPY .env .
EXPOSE 5000
RUN yarn build
# RUN yarn build
CMD ["yarn", "start"]